export const GET_LAUNCH_REQUEST = 'GET_LAUNCH_REQUEST';
export const GET_LAUNCH_SUCCESS = 'GET_LAUNCH_SUCCESS';
export const GET_LAUNCH_FAIL = 'GET_LAUNCH_FAIL';

export const GET_LAUNCH_BY_ID_REQUEST = 'GET_LAUNCH_BY_ID_REQUEST';
export const GET_LAUNCH_BY_ID_SUCCESS = 'GET_LAUNCH_BY_ID_SUCCESS';
export const GET_LAUNCH_BY_ID_FAIL = 'GET_LAUNCH_BY_ID_FAIL';
